
# 同一discovery集群的所有node节点地址，包含本node
nodes = ["127.0.0.1:7171"]
enableprotect=false

# 本可用区zone(一般指机房)标识
[env]
region = "sh"
zone = "sh001"
host = "test1"
DeployEnv = "dev"


# 其他可用区zone访问host和其标识
# [zones]
# "sh002" = ["10.2.0.10:7171", "10.2.0.11:7171", "10.2.0.12:7171"]
# "sh003" = ["10.3.0.10:7171", "10.3.0.11:7171", "10.3.0.12:7171"]

# 本节点监听端口
# 注意：ip别配置为0.0.0.0或者127.0.0.1
[httpServer]
addr = "127.0.0.1:7171"
timeout="40s"

# 当前节点同步其他节点使用的http client
# dial 连接建立超时时间
# keepAlive 连接复用保持时间
[httpClient]
dial = "1s"
keepAlive = "120s"
timeout="40s"

[log]
stdout = true
